version: '3.8'

services:
  db:
    image: mysql:8.1.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: foodtech
      MYSQL_USER: fooduser
      MYSQL_PASSWORD: password123
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  db_data:
